### ISSUE TITLE
Create UI component for the currently watched folders

### ISSUE THREAD

**Issue by dtap001** [TheT34m/ObsidianAndroidNotifications#10]
It should be a list where every folder is visible which is watched. This should be some kind of scrollable list. List item should contain:
- folder path
- last checked time
- delete button to remove the folder
- add button at the top to add new file

**Comment by mgulyas42** [comment]
I still get " Initializing WatchedFolders" logs when I closed the app and only the foreground service is running.

**Comment by dtap001** [comment]
implemented
