### ISSUE TITLE
Create a UI component to list currently scheduled system alarms

### ISSUE THREAD

**Issue by dtap001** [TheT34m/ObsidianAndroidNotifications#12]
The component should be some kind of scroll able list. The list item should contain:
- the title text of the reminder 
- scheduled time
- the file which contains the task entry
- updated on datetime stamp
- remove button to remove the alarm

**Comment by mgulyas42** [comment]
@dtap001 what do you think, how to list/store these informations?

At the moment we keep in the preferences only the requestId for the intent, to cancel it. In my opinion we should refactor it to store an object (as string or whatever) about these properties and we can listen for change in the UI.
I'm not sure is it the best way to persist everything, but maybe its the easier way

**Comment by dtap001** [comment]
I agree with extending the current ActiveReminder object with these data.
