### ISSUE TITLE
Task container

### ISSUE THREAD

**Issue by mgulyas42** [TheT34m/ObsidianAndroidNotifications#6]
## Goals
- [ ] Check foreground service is required for our goal
  - [ ] If we need this, how can we hide foreground notification
- [ ]  List reminders in the UI (automatically refresh)
- [ ] Change the notification icon

## Future goals:

- [ ] Reminder sound settings
- [ ] Change the App icon
- [ ] Make a UI for sound settings

**Comment by dtap001** [comment]
I have dissected this to separate tasks
